# See https://docs.rubocop.org/rubocop/configuration

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable

Layout/LineLength:
  Exclude:
    - "spec/**/*_spec.rb"

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"
    - "db/seeds.rb"
    - "config/environments/**/*.rb"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*.rb"

RSpec/LetSetup:
  Exclude:
    - "spec/**/*_spec.rb"

RSpec/EmptyExampleGroup:
  Exclude:
    - "spec/integration/**/*_spec.rb"

RSpec/MultipleExpectations:
  Exclude:
    - "spec/**/*.rb"

RSpec/ExampleLength:
  Exclude:
    - "spec/**/*.rb"

Rails/ReversibleMigration:
  Exclude:
    - "db/migrate/*.rb"

Style/Documentation:
  Enabled: false
