version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:alpine3.16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=dealership
      - PG_DATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis:alpine3.16
    ports:
      - 6379:6379
volumes:
  postgres_data:
