default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  username: <%= ENV.fetch('DB_USER', 'dealership') %>
  password: <%= ENV.fetch('DB_PASS', 'password') %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>

development:
  <<: *default
  database: dealership_development

test:
  <<: *default
  database: dealership_test

production:
  <<: *default
  database: dealership_production
  username: dealership
  password: <%= ENV["DEALERSHIP_DATABASE_PASSWORD"] %>
